version: 2.1
orbs:
  terraform: circleci/terraform@3.1.0
  azure-cli: circleci/azure-cli@1.0.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - terraform/install:
          terraform_version: '1.2.8' 
  verify-install:
    executor: azure-cli/default
    steps:
      - azure-cli/install
      - run:
          command: az -v
          name: Verify Azure CLI is installed

    

workflows:
    example-workflow:
      jobs:
        - terraform/init:
            checkout: true 
            attach-workspace: true 
            resource_class: medium 
            path: terraform
            tag: '1.0.0' 
            workspace-root-dir: . 
            timeout: '10m'

        - terraform/plan:
            workspace-root: . 
            attach-workspace: true 
            checkout: true 
            persist-workspace: true 
            out: plan.out 
            path: terraform 
            resource_class: medium 
            tag: '1.0.0' 
            timeout: '10m' 
        
        

           
        